import '../css/app.css';
import {createInertiaApp,Head,Link,router,useForm,usePage} from '@inertiajs/react';
import {createRoot} from 'react-dom/client';
import React,{PropsWithChildren} from 'react';
type Shared={auth:{user:null|{name:string;email:string}},locale:'en'|'ar',flash:{success?:string}};
const tr=(l:string,en:string,ar:string)=>l==='ar'?ar:en;
function Layout({children}:PropsWithChildren){const {auth,locale,flash}=usePage<Shared>().props;return <div dir={locale==='ar'?'rtl':'ltr'}><div className="bg-amber-300 px-4 py-2 text-center text-xs font-bold tracking-widest">DEMO — NOT OFFICIAL · SYNTHETIC DATA ONLY</div><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between p-4"><Link href="/dashboard" className="text-xl font-black text-indigo-800">Cornerstone <span className="text-teal-600">SIS</span></Link>{auth.user&&<nav className="flex gap-4 text-sm"><Link href="/applications">{tr(locale,'Applications','الطلبات')}</Link><Link href="/registration">{tr(locale,'Registration','التسجيل')}</Link><Link href="/finance">{tr(locale,'Finance','المالية')}</Link></nav>}<div className="flex gap-2"><button className="rounded border px-2" onClick={()=>router.post('/locale',{locale:locale==='en'?'ar':'en'})}>{locale==='en'?'العربية':'English'}</button>{auth.user&&<button onClick={()=>router.post('/logout')} className="text-sm">{tr(locale,'Sign out','خروج')}</button>}</div></div></header>{flash.success&&<div className="mx-auto mt-4 max-w-7xl rounded bg-emerald-100 p-3">{flash.success}</div>}<main className="mx-auto max-w-7xl p-6">{children}</main></div>}
function AuthCard({title,children}:PropsWithChildren<{title:string}>){return <main className="grid min-h-screen place-items-center bg-indigo-950 p-6"><div className="w-full max-w-md rounded-2xl bg-white p-8 shadow-2xl"><div className="mb-1 text-xs font-bold text-amber-600">DEMO — NOT OFFICIAL</div><h1 className="mb-6 text-2xl font-black">{title}</h1>{children}</div></main>}
function Input(p:React.InputHTMLAttributes<HTMLInputElement>){return <input {...p} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 focus:border-indigo-600 focus:outline-none"/>}
function Login(){const f=useForm({email:'applicant@example.test',password:'DemoPassword123!',remember:false});return <AuthCard title="Cornerstone SIS"><Head title="Sign in"/><form onSubmit={e=>{e.preventDefault();f.post('/login')}} className="space-y-4"><label>Email<Input type="email" value={f.data.email} onChange={e=>f.setData('email',e.target.value)}/></label><label>Password<Input type="password" value={f.data.password} onChange={e=>f.setData('password',e.target.value)}/></label>{Object.values(f.errors).map((x,i)=><p key={i} className="text-red-700">{x}</p>)}<button className="w-full rounded-lg bg-indigo-700 p-3 font-bold text-white">Sign in</button><Link href="/register" className="block text-center text-indigo-700">Create applicant account</Link></form></AuthCard>}
function Register(){const f=useForm({given_name:'',family_name:'',email:'',password:'',password_confirmation:'',locale:'en'});return <AuthCard title="Applicant registration"><form onSubmit={e=>{e.preventDefault();f.post('/register')}} className="space-y-3">{(['given_name','family_name','email','password','password_confirmation'] as const).map(k=><label key={k} className="block capitalize">{k.replaceAll('_',' ')}<Input type={k.includes('password')?'password':k==='email'?'email':'text'} value={f.data[k]} onChange={e=>f.setData(k,e.target.value)}/></label>)}{Object.values(f.errors).map((x,i)=><p key={i} className="text-red-700">{x}</p>)}<button className="w-full rounded-lg bg-indigo-700 p-3 font-bold text-white">Create account</button></form></AuthCard>}
function Dashboard({metrics}:{metrics:Record<string,number>}){return <Layout><Head title="Dashboard"/><h1 className="text-3xl font-black">Student information, connected.</h1><p className="mt-2 text-slate-600">Admissions, academics, accounts, and Moodle integration in one auditable system.</p><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(metrics).map(([k,v])=><div key={k} className="rounded-xl border bg-white p-5 shadow-sm"><div className="text-sm capitalize text-slate-500">{k.replace(/([A-Z])/g,' $1')}</div><div className="mt-2 text-3xl font-black text-indigo-800">{v}</div></div>)}</div></Layout>}
function Applications({applications,programs}:{applications:any[],programs:any[]}){return <Layout><h1 className="text-2xl font-black">Applications</h1><div className="mt-5 space-y-3">{applications.length?applications.map(a=><div key={a.id} className="rounded-xl border bg-white p-4"><b>{a.application_number}</b> · {a.program?.name_en}<span className="float-end rounded-full bg-indigo-100 px-3 py-1 text-xs">{a.status}</span></div>):<p>No applications yet. Available programs: {programs.map(p=>p.name_en).join(', ')||'catalog setup pending'}.</p>}</div></Layout>}
function Registration({sections}:{sections:any[]}){return <Layout><h1 className="text-2xl font-black">Registration</h1><p className="mt-2 text-slate-600">Capacity and timetable conflicts are checked atomically.</p><div className="mt-5 grid gap-3">{sections.map(s=><article key={s.id} className="rounded-xl border bg-white p-4"><b>{s.code}</b> — {s.course_version?.course?.title_en}<div className="text-sm text-slate-500">Capacity {s.capacity}</div></article>)}{!sections.length&&<p>No open sections.</p>}</div></Layout>}
function Finance({balances,transactions}:{balances:any[],transactions:any[]}){return <Layout><h1 className="text-2xl font-black">Student account</h1><div className="my-5 flex gap-3">{balances.map(b=><div key={b.currency} className="rounded-xl bg-indigo-900 p-5 text-white"><small>{b.currency}</small><div className="text-2xl font-black">{b.balance}</div></div>)}</div>{transactions.map(x=><div key={x.id} className="border-b bg-white p-3">{x.description}<span className="float-end">{x.currency}</span></div>)}</Layout>}
const pages:Record<string,React.ComponentType<any>>={'Auth/Login':Login,'Auth/Register':Register,'Dashboard':Dashboard,'Applications/Index':Applications,'Registration/Index':Registration,'Finance/Index':Finance};
createInertiaApp({resolve:name=>pages[name],setup:({el,App,props})=>createRoot(el).render(<App {...props}/>),progress:{color:'#4338ca'}});
